kind: pipeline
type: kubernetes
name: build-amd64
platform:
  arch: amd64
node_selector:
  kubernetes.io/arch: amd64

steps:
  - name: submodules
    image: alpine/git
    commands:
      - git submodule update --init --recursive

  - name: build-amd64
    image: debian:bookworm-slim
    commands:
        - apt-get update
        - apt-get -qy install gcc-12 cmake make build-essential 
        - mkdir build
        - cd build; cmake ..
        - make -j 4 
        - make test

--- 
kind: pipeline
type: kubernetes
name: build-arm64
platform:
  arch: arm64
node_selector:
  kubernetes.io/arch: arm64

steps:
  - name: submodules
    image: alpine/git
    commands:
      - git submodule update --init --recursive

  - name: build-arm64
    image: debian:bookworm-slim
    commands:
        - apt-get update
        - apt-get -qy install gcc-12 cmake make build-essential
        - mkdir build
        - cd build; cmake ..
        - make -j 4 
        - make test

---

kind: pipeline
type: kubernetes
name: mirror-to-github
node_selector:
  kubernetes.io/arch: amd64
  federationhq.de/location: Blumendorf
  federationhq.de/compute: true
steps:
  - name: github-mirror
    image: registry.cloud.federationhq.de/drone-github-mirror:latest
    pull: always
    settings:
      GH_TOKEN: 
        from_secret: GH_TOKEN
      GH_REPO: "byterazor/EventManager"
      GH_REPO_DESC: "very simple C++ Event System"
      GH_REPO_HOMEPAGE: "https://rm.byterazor.de/projects/eventmanager"
depends_on:
  - build-amd64
  - build-arm64


--- 
kind: secret
name: GH_TOKEN
get:
  path: github
  name: token